name: Link Check
on:
  pull_request:
    paths:
      - '**/*.md'
jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress **/*.md
